##add this to prometheus.yml
groups:
  - name: kubernetes-pod-memory-alerts
    rules:
    - alert: HighMemoryUsage
      expr: sum(container_memory_usage_bytes{image!=""}) by (pod_name) / sum(kube_pod_container_resource_limits_memory_bytes) by (pod) > 0.9
      for: 10m
      labels:
        severity: critical
      annotations:
        summary: "High Memory usage detected for pod {{ $labels.pod_name }}"
        description: "Pod {{ $labels.pod_name }} is using more than 90% of its allocated memory."
